print("Gerson O. Pantoja")
print("Masiga, Gasan, Marinduque")
print("October 22, 2001")
print("Marinduque State College")
print("Information Technology")
print("Second Year")
print("Section C")
print("Watching Films")
print("Cooking")
print("Listening to music")
print("Reading a book/e-book")
print("Declutter/organize personal things")
